apiVersion: v1
kind: Pod
metadata:
  name: ip-app
spec:
  containers:
  - name: ip-app
    image: harshajain/ip_app:2
    ports:
    - containerPort: 80
    env:
    - name: DB_URL
      valueFrom:
        configMapKeyRef:
          name: my-cm
          key: db_url
    - name: DB_USER
      valueFrom:
        configMapKeyRef:
          name: my-cm
          key: db_user
