apiVersion: v1
kind: Pod
metadata:
  name: ip-app-resource-quota
spec:
  containers:
  - name: ip-app
    image: harshajain/ip_app
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: 200Mi
        cpu: 250m
      limits:
        memory: 150Mi
        cpu: 500m
  priorityClassName: high-priority
