
pipeline {
    
    agent {label 'slave'}
    
    environment {
        IMAGE_TAG = "${BUILD_NUMBER}"
    }
    
    stages {
        
        stage('Checkout'){
           steps {
                git credentialsId: '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', 
                url: 'https://github.com/Hareeshyadavn/Hareeshyadavn.git',
                branch: 'new-branch'
           }
        }

        stage('Build Docker'){
            steps{
                script{
                    sh '''
                    echo 'Build Docker Image'
                    cd python-jenkins-argocd-k8s/
                    docker build -t yadavn1692/repositry1:v2 . 
                    '''
                }
            }
        }

        stage('Push the artifacts'){
           steps{
                script{
                    sh '''
                    echo 'Push to Repo'
                    docker push yadavn1692/repositry1:v2
                    '''
                }
            }
        }
        
        stage('Checkout K8S manifest SCM'){
            steps {
                git credentialsId: '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', 
                url: 'https://github.com/Hareeshyadavn/Hareeshyadavn.git',
                branch: 'new-branch'
            }
        }
        
        stage('Update K8S manifest & push to Repo'){
            steps {
                script{
                    withCredentials([usernamePassword(credentialsId: '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', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
                        sh '''
                        cd /python-jenkins-argocd-k8s/deploy/
                        cat deploy.yaml
                        sed -i '' "s/v2/v3/g" deploy.yaml
                        cat deploy.yaml
                        git add deploy.yaml
                        git commit -m 'Updated the deploy yaml | Jenkins Pipeline'
                        git remote -v
                        git push https://github.com/Hareeshyadavn/Hareeshyadavn.git HEAD:new-branch
                        '''                        
                    }
                }
            }
        }
    }
}
