apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-app-argo-config
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Hareeshyadavn/Hareeshyadavn.git
    targetRevision: main
    path: kubernetes/argocd/sample
  destination:
    server: https://172.31.37.199:6443
    namespace: new-app
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
