apiVersion: v1
kind: Pod
metadata:
  name: pvc-mount-pod
spec:
  containers:
  - name: my-contaier
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: pvc-vol
      mountPath: /app/pvc-volume
  volumes:
  - name: pvc-vol
    persistentVolumeClaim:
      claimName: my-pvc-ebs1
