pipeline {
   agent any 

   tools {
      maven 'maven-3.9.2'
   }

   stages {
      stage('BUILD') {
         steps {
               sh ''' 
                  cd ITD-maven/maven/calculator_app
                  mvn clean package -Dmaven.test.skip=true
               '''
         }
      }

      stage('UNIT TEST') {
         steps {
            dir("ITD-maven/maven/calculator_app") {
               sh 'mvn clean test'
            }
         }
      }

      stage('Integration TEST') {
         steps {
            dir("ITD-maven/maven/calculator_app") {
               sh 'sudo mvn clean integration-test'
            }
         }
      }

      // stage('Deploy Tomcat Using maven plugin') {
      //    steps {
      //       dir("ITD-maven/maven/calculator_app") {
      //          sh 'sudo mvn tomcat7:deploy'
      //       }
      //    }
      // }

      stage ('Deploy Tomcat Using jenkins plugin') {
         steps {
                script {
                    deploy adapters: [tomcat9(credentialsId: 'manager', path: '', url: 'http://13.49.222.53:8091/')], 
                                     contextPath: '/calculator', 
                                     war: 'maven/calculator_app/target/calculator.war'
                }
         }
      }
   }
}
