---
- name: play2
  hosts: localhost
  tasks:
  - name: install some packages ubuntu
    become: true
    apt:
      name: tree
      state: present
    register: install_out
  - name: install some packages rhel
    become: true
    yum:
      name: tree
      state: present
    register: install_out
    ignore_errors: true


  - name: check working directory
    command: 'pwd'
    register: pwd_out

  - name: print the output from previous command
    debug: var=pwd_out.stdout  
  - name: print output
    debug: 
      msg: output of previous command {{ pwd_out.stdout }}
    when: pwd_out.stdout is defined
   
