---
- hosts: all 
  tasks:
  - name: install httpd
    become: true
    ansible.builtin.apt:
      name: git
      state: present
  - name: create empty file
    file:
      path: /home/ubuntu/test
      state: touch

  - name: copy file
    copy:
      src: /home/ubuntu/test
      dest: /home/ubuntu/some_directory/copy_test

