---
- name: play1
  hosts: all
  tasks:
  - name: install set of packages
    become: true
    apt:
      name: "{{item }}"
      state: present
    with_items:
    - jq
    - git
    - bc
  ignore_errors: true

- name: play2
  hosts: localhost
  tasks:
  - name: install set of packages
    become: true
    apt:
      name: "{{item }}"
      state: present
    loop:
    - jq
    - git
    - bc
    - apache2
    register: install_output
    ignore_errors: true

  - name: print output
    debug: 
      var: install_output.results.ansible_loop_var

  - name: check service
    service:
      name: apache2
      state: started
