
pipeline{
	agent {label 'slave3'}
	tools{
	maven '3.9.5'
	}
	stages{
		stage ('BUILD'){
			steps{
				sh 'mvn clean package'
			}
			post{
			success{
			echo "archiving artifacts"
			archiveArtifacts artifacts: '**target/*.war'
		}
			}
		}
		stage ('DEPLOY'){
			steps{
			deploy adapters: [tomcat9(credentialsId: 'tomcat-manager', path: '', url: 'http://16.16.64.186:8091/')], contextPath: null, war: '**/*.war'
			}
		}
	}
}
