
pipeline{
	agent any
	tools{
	maven '3.9.5'
	}
	stages{
		stage ('BUILD'){
			steps{
				sh '''cd ./newproj1/samplewar/
				mvn clean package '''
			}
			post{
			success{
			echo "archiving artifacts"
			archiveArtifacts artifacts: 'newproj1/samplewar/**target/*.war'
		}
			}
		}
		stage ('DEPLOY'){
			steps{
			deploy adapters: [tomcat9(credentialsId: 'tomcat-manager', path: '', url: 'http://13.201.121.124:8091')], contextPath: '/devOpsWeb',onFailure: false, war: 'newproj1/samplewar/**target/*.war'
			}
		}
	}
}
