
pipeline{
	agent {label 'slave4'}
	tools{
	maven 'maven'
	}
	stages{
		stage ('BUILD'){
			steps{
				sh '''cd ./newproj1/samplewar/
				mvn clean package '''
			}
			post{
			success{
			echo "archiving artifacts"
			archiveArtifacts artifacts: 'newproj1/samplewar/**target/*.war'
		}
			}
		}
		stage ('DEPLOY'){
			steps{
			deploy adapters: [tomcat9(credentialsId: 'tomcat-manager', path: '', url: 'http://16.170.155.136:8091/')], contextPath: '/devOpsWeb', war: 'newproj1/samplewar/**target/*.war'
			}
		}
	}
}
