apiVersion: v1
kind: Pod
metadata:
  name: with-node-affinity2
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: env
            operator: In
            values:
            - tes
            - pro
  containers:
  - name: ip-app
    image: yadavn1692/repositry1:1
    ports:
    - containerPort: 8080
