apiVersion: v1
kind: Pod
metadata:
  name: with-node-affinity-test
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: env
            operator: In
            values:
            - test
            - stagging
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
