apiVersion: v1
kind: Pod
metadata:
  name: with-node-antiaffinity-test
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: environment
            operator: In
            values:
            - test
            - prod
        topologyKey: topology.kubernetes.io/zone
           
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        podAffinityTerm:
        - labelSelector:
            matchExpressions:
            - key: env
              operator: In
              values:
              - qa
          topologyKey: topology.kubernetes.io/zone
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
