apiVersion: apps/v1
kind: Deployment
metadata:
  name: ip-app-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: ip-app
  template:
    metadata:
      labels:
        app: ip-app
    spec:
      nodeSelector:
        environment: test
      containers:
      - name: ip-app
        image: 
        ports:
        - containerPort: 80
