pipeline{
  agent { label "jenins-agent" }
  environment {
    APP_NAME = "welcome-app"
  }
  stages {
    stage("Cleanup Workspace") {
            steps {
                cleanWs()
            }
        }

        stage("Checkout from SCM") {
               steps {
                   git branch: 'main', credentialsId: 'Hareeshyadavan', url: 'https://github.com/Hareeshyadavn/Hareeshyadavn.git'
               }
        }

        stage("Update the Deployment Tags") {
            steps {
                sh """
                  pwd
                   cd kubernetes/argocd/sample/
                   pwd
                   cat deploy.yml
                   sed -i 's/${APP_NAME}.*/${APP_NAME}:${IMAGE_TAG}/g' deploy.yml
                   cat deploy.yml
                """
            }
        }

        stage("Push the changed deployment file to Git") {
            steps {
                sh """
                   git config --global user.name "Hareeshyadavn"
                   git config --global user.email "hareesh1692@gmail.com"
                   cd kubernetes/argocd/sample/
                   git add deploy.yml
                   git commit -m "Updated Deployment Manifest"
                """
                withCredentials([gitUsernamePassword(credentialsId: 'Hareeshyadavan', gitToolName: 'Default')]) {
                  sh "git push https://github.com/Hareeshyadavn/Hareeshyadavn main"
                }
            }
        }
      
    }
}
