apiVersion: batch/v1
kind: Job
metadata:
  name: jobs-example
spec:
  template:
    spec:
      containers:
      - name: busybox
        image: busybox
        command:
        - /bin/sh
        - -c
        - "sleep 10"
      restartPolicy: Never
  backoffLimit: 10
<<<<<<< HEAD
  completions: 5
  parallelism: 3 
  activeDeadlineSeconds: 1000
=======
  completions: 2
  activeDeadlineSeconds: 300
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> new-branch
>>>>>>> main
=======
>>>>>>> new-branch
>>>>>>> main
=======
>>>>>>> new-branch
>>>>>>> main
=======
>>>>>>> new-branch
>>>>>>> main
