apiVersion: batch/v1
kind: Job
metadata:
  name: jobs-example
spec:
  template:
    spec:
      containers:
      - name: busybox
        image: busybox
        command:
        - /bin/sh
        - -c
        - "sleep 10"
      restartPolicy: OnFailure
  backoffLimit: 10
  completions: 2
