apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-contaier
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: hostpath-vol
      mountPath: /app/volume
  volumes:
  - name: hostpath-vol
    hostPath:
      path: /home/ubuntu/pod_data
      type: DirectoryOrCreate
