apiVersion: apps/v1
kind: Deployment
metadata:
  name: ip-app-deployment1
spec:
  replicas: 5
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: my-container
        image: harshajain/ip_app:2
        ports:
          - containerPort: 8080

