apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ip-app-statefulset	 
spec:
  replicas: 4
  selector:
    matchLabels:
      app: ip-app
  template:
    metadata:
      labels:
        app: ip-app
    spec:
      containers:
      - name: ip-app
        image: harshajain/ip_app:2
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: head-svc
spec:
  clusterIP: None
  selector:
    app: ip-app
  ports:
  - name: http
    port: 30002
    targetPort: 8080
