apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: my-sa-clusterrole
rules:
- apiGroups: [""] 
  resources: ["deployment", "pods", "services","nodes"]
  verbs: ["get", "watch", "list"]
