apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  initContainers:
  - name: nginx
    image: nginx
    command: ["/bin/sh"]
    args: ["-c", "echo 'This is nginx init container'; sleep 20"]
  containers:
  - name: busybox1
    image: busybox
    ports:
    - conatinerPort: 80
    volumeMounts:
    - name: my-vol
      mountPath: /app/volume
  - name: busybox2
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "while true; do ls /var/log/nginx; cat /var/log/nginx/access.log; sleep 5; done"]
    volumeMounts:
    - name: my-vol
      mountPath: /app/volume
  volumes:
  - name: my-vol
    hostPath:
      path: /home/ubuntu/pod_data
      type: DirectoryOrCreate
