apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ip-app-daemonset
spec:
  selector:
    matchLabels:
      app: prod
  template:
    metadata:
      labels:
        app: prod
    spec:
      containers:
      - name: new-contaier
        image: harshajain/ip_app:2
        ports:
        - containerPort: 8080
