#!/bin/bash
# run with sudo previlage
#install httpd (amazon Linux 2version)

echo "---update the linux----"

sudo yum update -y

echo "---installing httpd----"

sudo yum install -y httpd

echo "----enable httpd in linux----"

sudo systemctl enable httpd

echo "----starting httpd in linux----"

sudo systemctl start httpd

echo "----creating index.html file in path /var/www/html/----"

sudo echo "<h1> hello this is $(hostname -f) <h1>" > /var/www/html/index.html
