pipeline {
    agent {label 'slave2'}
	tools{
	maven 'maven-3.9.5' 
		}
    stages {
        stage('Build') {
            steps {
		  cd ./newproject/  
                sh 'mvn package'
		    
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }
        stage('Deploy') {
            steps {
                script{
		deploy adapters: [tomcat9(credentialsId: 'tomcat_manager', path: '', url:'http//51.20.104.76:8091')],
					contextPath: '/sample.jar',
					onFailure: false,
					war: 'newproject/target/sample.jar'
		}
            }
        }
    }
}
