pipeline {
    agent {label 'slave2'}
	tools{
	maven 'maven-3.9.5' 
		}
    stages {
        stage('Build') {
            steps {
                sh 'mvn package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }
        stage('Deploy') {
            steps {
                script{
		deploy adapters: [tomcat9(credentialsId: 'tomcat_manager', path: '', url:'http//13.51.174.66:8081')],
					contextPath: '/gs-maven-0.1.0.jar',
					onFailure: false,
					war: 'newproject/target/gs-maven-0.1.0.jar'
		}
            }
        }
    }
}
