pipeline {
    agent any
	tools{
	maven '3.9.5' 
		}
    stages {
        stage('Build') {
            steps {
		 sh ''' cd ./newproject/  
                        mvn package '''
		    
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }
        stage('Deploy') {
            steps {
                script{
		deploy adapters: [tomcat9(credentialsId: 'tomcat_manager', path: '', url:'http//13.51.241.193:8091')],
					contextPath: '/sample.jar',
					onFailure: false,
					war: 'newproject/target/sample.jar'
		}
            }
        }
    }
}
